language: python
python:
- 2.7
- 3.6
- 3.5
- 3.4
- 3.3
sudo: false
install:
- travis_retry pip install pyflakes
- travis_retry pip install yamllint
- travis_retry pip install demjson
script:
- pyflakes drupal/build.sh
- yamllint .
- find . -name \*.json | xargs -I {} jsonlint {}
after_success:
- travis_retry pip install pep8
- pep8 --statistics --count drupal/build.sh
matrix:
  fast_finish: true
  allow_failures:
  - python: 3.6
  - python: 3.5
  - python: 3.4
  - python: 3.3
notifications:
  email: false
  slack:
    on_success: never
    on_failure: always
    secure: Fv6McQHQdFOxeV0gjyfpPjN/80Ej4BPHdSSAutvQmR+RViK9gOMI3exmnMoOvp+BBbEJ47YhPqP2fCvlvstXyCMn/e5x7UswBvcpu8UR39f17cKw8jlCHDXAkUGuImasVvh2cPME6wy8QTOVj/7EwDd36VyChHyZA2BjnVF4Cxf3hOHlBKQ+juoLkge3etjCYubhCfCMRmm5tTYo9nR0OVVAad4wlqeyBkLhXfdXt4j3Fq8571OPCuHTciSOQASxAdGPD6FK+8MuKvo3XkUfmeuHNY/tapYoqyzfvy5hwTwAypcBzQX5wDZD7j3e9HScj+TAxLSbIgk9YC7/nqDmcHsR7H8+6HEJuxpaLmMUYI51VNXx+RtCcTrxHbxfC0G17C2I37ldHaJQbFW7cqDYZ2ZHbGQ4ovCqeKcbirRoIib3wy20lpDZKBXP+gcbBLh+n966w4j14G0h0mPBUxW0Ys19Sx+99rizciXn7xmILaO8k+sj55xui6AsSjqihlE1shEEruT0ijhGkxLf3RbDd8M58lnsrnlrxDfwYY4EPZoyPu1oWprgrIumz6EVr38gygFsPNPI95zlsXLMqzO4Od4+xUUB4vaV49Rv5c7rSRgNGfCXYBI79LR78rWjWPZYkbjzb8Piz63v202i1YkkADMQk87yDk/LQWM9Aa9IM6Y=
