---
# file: roles/web-front/tasks/php53u.yml

# Install all php packages
  - name: Install php-fpm
    yum: pkg={{ php_package }}-fpm state=installed
  - name: Ensure php-fpm is running now and on boot
    service: name=php-fpm state=started enabled=yes
  - name: Install php packages
    yum: pkg={{ item }} state=installed
    with_items:
      - "{{ php_package }}"
      - "{{ php_package }}-mysql"
      - "{{ php_package }}-gd"
      - "{{ php_package }}-imap"
      - "{{ php_package }}-mbstring"
      - "{{ php_package }}-pear"
      - "{{ php_package }}-xml"
      - "{{ php_package }}-xmlrpc"
      - "{{ php_package }}-pdo"
      - "{{ php_package }}-pecl-memcache"
      - "{{ php_package }}-pecl-memcached"
      - "{{ php_package }}-pecl-apc"
      - "{{ php_package }}-devel"
      - "{{ php_package }}-dba"
      - "{{ php_package }}-mcrypt"
      - "{{ php_package }}-soap"
      - "{{ php_package }}-pecl-redis"
      - "{{ php_package }}-suhosin"
