
  - name: Install JRE
    yum: pkg=jre state=installed

  - name: Make sure {{ cache_path }} exists
    action: file path={{ cache_path }} state=directory

  - name: Download solr
    shell: curl --retry 5 -s -o "{{ cache_path }}/solr-{{ solr_version }}.tgz" "{{ solr_url }}{{ solr_version }}/solr-{{ solr_version }}.tgz"
      creates="{{ cache_path }}/solr-{{ solr_version }}.tgz"

  - name: Create group for solr
    group: name=solr    

  - name: Create user for solr
    user: name=solr
          home={{ solr_path }}
          group=solr

  - name: Ensure solr dir exists
    action: file path={{ solr_path }} state=directory owner={{ solr_user }} group={{ solr_group }} mode=0755

  - name: Ensure log dir exists
    action: file path={{ solr_log_path }} state=directory owner={{ solr_user }} group={{ solr_group }}

  - name: Unpack solr
    shell: tar xfz "{{ cache_path }}/solr-{{ solr_version }}.tgz" -C {{ solr_path }} --strip-components 1
      creates="{{ solr_path }}/example"

  - name: Chown solr installation
    shell: chown -R {{ solr_user }}:{{ solr_group }} {{ solr_path }}

  - name: Create collection for Drupal
    shell: cp -r {{ solr_path }}/example {{ solr_path }}/drupal
      creates="{{ solr_path }}/drupal"

  - name: Solr init.d file
    copy: src=solr_init dest=/etc/init.d/solr mode=0755

  - name: Solr sysconfig file
    template: src=solr_sysconfig.j2 dest=/etc/sysconfig/solr
    notify:
      - restart solr
