
# Init tasks
- name: ensure iptables is stopped and is not running at boot time.
  action: service name=iptables state=stopped enabled=no

# Configuration for yum
- name: Provision yum.conf
  ini_file: dest=/etc/yum.conf
    section="{{ item.0.section }}"
    option="{{ item.1.key }}"
    value="{{ item.1.val }}"
    backup=yes
  with_subelements:
    - "{{ yum }}"
    - options

# Repos
- name: Enable epel repository
  shell: rpm -Uvh http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm
    creates=/etc/yum.repos.d/epel.repo

- name: Enable remi repository
  shell: rpm -Uhv http://rpms.famillecollet.com/enterprise/remi-release-6.rpm
    creates=/etc/yum.repos.d/remi.repo

- name: Enable ius repository
  shell: rpm -Uhv http://dl.iuscommunity.org/pub/ius/stable/CentOS/6/x86_64/ius-release-1.0-13.ius.centos6.noarch.rpm
    creates=/etc/yum.repos.d/ius.repo

- name: Enable WK repository
  shell: rpm -Uhv https://wkrepo:xeehae9eeX@repo.wunder.io/CentOS/6/x86_64/wk-release-0.1-1.WK.x86_64.rpm
    creates=/etc/yum.repos.d/wk.repo

# Basic packages
- name: Install yum utils
  yum: pkg={{ item }} state=present
  with_items:
    - yum-utils
    - yum-presto

# Refresh closest mirror cache
#- file: path=/var/cache/yum/x86_64/6/timedhosts.txt state=absent

# Basic packages
- name: Install packages
  yum: pkg={{ item }} state=present
  with_items:
    - ntp
    - screen
    - htop
    - ntop
    - nano
    - iotop
    - wget
    - perl
    - perl-DBI
    - gcc
    - cvs
    - subversion
    - gitosis
    - git
    - vim
    - make
    - unzip
    - patch
    - yum-plugin-security
    - libselinux-python
    - links
    - sysstat
    - GraphicsMagick
    - python-yaml

# Utils
- name: set SELinux to disabled
  action: selinux state=disabled

- name: be sure ntp is configured
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  notify:
    - restart ntpd
  tags: ntp

- name: ensure ntpd is running now and on boot
  service: name=ntpd state=started enabled=yes
  tags: ntp

- name: be sure sysctl.conf is configured
  template: src=sysctl.conf.j2 dest=/etc/sysctl.conf

- name: be sure 90-nproc.conf is configured
  template: src=90-nproc.conf.j2 dest=/etc/security/limits.d/90-nproc.conf
