##
# CSS compiling tools.
#
- name: CSS | Install rubygems package
  yum: pkg=rubygems state=installed
  tags: css

- name: RUBY | Install Bundler
  shell: gem install bundler

- name: Development packages
  yum: pkg={{ item }} state=installed
  with_items:
    - "{{ development_packages }}"

- name: PHP | XDebug
  yum: pkg={{ php_package }}-pecl-xdebug state=installed
  tags: ntp

- name: PHP | Add section to the xdebug.ini file if it is missing
  lineinfile: dest=/etc/php.d/xdebug.ini
    regexp='^[XDebug]'
    insertbefore=BOF
    line='[XDebug]'

- name: PHP | Set up xdebug.ini
  ini_file: dest=/etc/php.d/xdebug.ini
    section={{ item.0.section }}
    option={{ item.1.key }}
    value={{ item.1.val }}
    backup=yes
  with_subelements:
    - "{{ xdebug }}"
    - options
  notify:
    - restart php-fpm

- name: MAILCATCHER | Install specific version of "tilt" gem because mailcatcher is picky
  gem: name="tilt" state=present user_install=no version=1.3.4

- name: MAILCATCHER | Install specific version of "mime-types" gem because mailcatcher is really picky
  gem: name="mime-types" state=present user_install=no version=1.25.1

- name: MAILCATCHER | Install mailcatcher gem
  gem: name="mailcatcher" state=latest user_install=no

- name: MAILCATCHER | Kill mailcatcher if it's running
  command: pkill mailcatcher
  ignore_errors: yes

- name: MAILCATCHER | Launch mailcatcher
  command: mailcatcher --ip=0.0.0.0

- name: MAILCATCHER | Add sendmail_path setting to {{ php_ini_file }}
  ini_file: dest={{ php_ini_file }}
    section="{{ item.0.section }}"
    option="{{ item.1.key }}"
    value="{{ item.1.val }}"
    backup=yes
  with_subelements:
    - "{{ php }}"
    - options
  notify:
    - restart php-fpm

- name: MAILCATCHER | Add mailcatcher command to rc.local to have it executed at startup
  lineinfile: dest=/etc/rc.d/rc.local
    regexp='^mailcatcher --http-ip=0\.0\.0\.0'
    insertbefore=BOF
    line='mailcatcher --http-ip=0.0.0.0'





