- name: Solr Rovio | Put solr configurations in place
  copy:
    src: solr_conf/
    dest: /usr/local/share/solr/drupal/solr/collection1/conf
    owner: solr
    group: solr
    mode: 0644
- name: Solr Rovio | Set correct name for solr collection
  template: src=core.properties.j2 dest=/usr/local/share/solr/drupal/solr/collection1/core.properties
  notify:
    - restart solr
